defaults: &defaults
  sessions:
    default:
      hosts:
        - <%= Figaro.env.mongodb_host %>
      database: <%= Figaro.env.mongodb_name %>
      options:
  options:
    raise_not_found_error: false

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
